# Generated by Django 3.2.9 on 2021-12-15 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
    ]
