# Generated by Django 3.2.9 on 2021-12-15 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
    ]
