# Generated by Django 3.2.9 on 2021-12-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_alter_tag_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام'),
        ),
    ]
